apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "order-service.fullname" . }}
  labels:
    {{- include "order-service.labels" . | nindent 4 }}
data:
  database.url: {{ .Values.config.database.url | quote }}
  database.username: {{ .Values.config.database.username | quote }}
  kafka.bootstrapServers: {{ .Values.config.kafka.bootstrapServers | quote }}
  redis.host: {{ .Values.config.redis.host | quote }}
  redis.port: {{ .Values.config.redis.port | quote }}