{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "bff.fullname" . }}
  labels:
    {{- include "bff.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "bff.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    {{- toYaml .Values.networkPolicy.ingress | nindent 4 }}
  egress:
    - to: []
      ports:
        - protocol: TCP
          port: 6379  # Redis
        - protocol: TCP
          port: 8081  # Order Service
        - protocol: TCP
          port: 8082  # Billing Service
        - protocol: TCP
          port: 8083  # Inventory Service
        - protocol: TCP
          port: 53    # DNS
        - protocol: UDP
          port: 53    # DNS
  {{- end }}