apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka.fullname" . }}-kafka
  labels:
    {{- include "kafka.labels" . | nindent 4 }}
    app.kubernetes.io/component: kafka
spec:
  type: {{ .Values.kafka.service.type }}
  ports:
    - port: {{ .Values.kafka.service.port }}
      targetPort: kafka
      protocol: TCP
      name: kafka
    - port: {{ .Values.kafka.service.internalPort }}
      targetPort: kafka-internal
      protocol: TCP
      name: kafka-internal
  selector:
    {{- include "kafka.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: kafka