image:
  repository: redis
  tag: "7-alpine"
  pullPolicy: IfNotPresent

auth:
  password: redis_password

service:
  type: ClusterIP
  port: 6379

persistence:
  enabled: true
  size: 5Gi
  storageClass: "standard"
  accessModes:
    - ReadWriteOnce

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

securityContext:
  runAsUser: 999
  runAsGroup: 999
  fsGroup: 999

podSecurityContext:
  runAsNonRoot: true

# Health checks
livenessProbe:
  exec:
    command:
      - redis-cli
      - ping
  initialDelaySeconds: 20
  periodSeconds: 5

readinessProbe:
  exec:
    command:
      - redis-cli
      - ping
  initialDelaySeconds: 5
  periodSeconds: 5

# Configurações do Redis
config:
  appendonly: "yes"
  save: "900 1 300 10 60 10000"
  maxmemory: "200mb"
  maxmemory-policy: "allkeys-lru"