# Configurações específicas para produção

replicaCount: 3

image:
  tag: "latest"
  pullPolicy: Always

app:
  profile: prod

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: 70

podDisruptionBudget:
  enabled: true
  minAvailable: 2

networkPolicy:
  enabled: true

config:
  database:
    url: jdbc:postgresql://techbra-postgres:5432/ecommerce_db
  kafka:
    bootstrapServers: techbra-kafka:29092
  redis:
    host: techbra-redis

# Configurações de produção adicionais
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 30

readinessProbe:
  initialDelaySeconds: 45
  periodSeconds: 15