# Valores padrão para o Order Service
replicaCount: 1

image:
  repository: techbra/order-service
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 65532

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 65532

service:
  type: ClusterIP
  port: 8081
  targetPort: 8081

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

# Horizontal Pod Autoscaler
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

# Pod Disruption Budget
podDisruptionBudget:
  enabled: true
  minAvailable: 1

# Network Policy
networkPolicy:
  enabled: true
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: techbra-ecommerce
      ports:
        - protocol: TCP
          port: 8081

# Configurações da aplicação
app:
  profile: prod
  port: 8081

# Health checks
livenessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: 8081
  initialDelaySeconds: 400
  periodSeconds: 30
  timeoutSeconds: 10
  failureThreshold: 5

readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: 8081
  initialDelaySeconds: 400
  periodSeconds: 20
  timeoutSeconds: 10
  failureThreshold: 5

# ConfigMap data
config:
  database:
    url: jdbc:postgresql://postgres:5432/ecommerce_db
    username: ecommerce_user
  kafka:
    bootstrapServers: kafka-kafka:9092
  redis:
    host: redis
    port: 6379

nodeSelector: {}

tolerations: []

affinity: {}