# Zookeeper configuration
zookeeper:
  enabled: true
zookeeper:
  image:
    repository: zookeeper
    tag: "3.8"
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 2181

  persistence:
    enabled: true
    size: 5Gi
    storageClass: "standard"

  resources:
    limits:
      cpu: 250m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi

  config:
    clientPort: 2181
    tickTime: 2000

# Kafka configuration
kafka:
  image:
    repository: confluentinc/cp-kafka
    tag: "7.5.0"
    pullPolicy: IfNotPresent

  replicaCount: 1

  service:
    type: ClusterIP
    port: 9092
    internalPort: 9092

  persistence:
    enabled: true
    size: 10Gi
    storageClass: "standard"

  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 512Mi

  config:
    brokerId: 1
    autoCreateTopics: true
    deleteTopicEnable: true
    logRetentionHours: 168
    numPartitions: 3
    defaultReplicationFactor: 1
    offsetsTopicReplicationFactor: 1
    transactionStateLogReplicationFactor: 1
    transactionStateLogMinIsr: 1
    heapOpts: "-Xmx512M -Xms512M"

  # Tópicos pré-criados
  topics:
    - name: order.events
      partitions: 3
      replicationFactor: 1
    - name: billing.events
      partitions: 3
      replicationFactor: 1
    - name: inventory.events
      partitions: 3
      replicationFactor: 1
    - name: notification.events
      partitions: 3
      replicationFactor: 1

# Kafka UI (opcional)
kafkaUi:
  enabled: false
  image:
    repository: provectuslabs/kafka-ui
    tag: "latest"
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 8080

  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi