# Configurações específicas para produção

replicaCount: 4

image:
  tag: "latest"
  pullPolicy: Always

app:
  profile: prod

resources:
  limits:
    cpu: 1500m
    memory: 1Gi
  requests:
    cpu: 750m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 4
  maxReplicas: 15
  targetCPUUtilizationPercentage: 50
  targetMemoryUtilizationPercentage: 60

podDisruptionBudget:
  enabled: true
  minAvailable: 2

networkPolicy:
  enabled: true

config:
  redis:
    host: techbra-redis
  microservices:
    orderService: http://order-service:8081
    billingService: http://billing-service:8082
    inventoryService: http://inventory-service:8083
  webclient:
    connectionTimeout: 2000
    readTimeout: 5000
    writeTimeout: 5000

# Configurações de produção adicionais
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 30

readinessProbe:
  initialDelaySeconds: 45
  periodSeconds: 15