spring:
  application:
    name: bff

  profiles:
    active: dev
  
  # Kafka Configuration for Event Listening
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: bff-cache-invalidation
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: "*"
  
  # Cache Configuration
  cache:
    type: redis

  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

server:
  port: 8084

# WebClient Configuration
webclient:
  connection-timeout: 5000
  read-timeout: 10000
  write-timeout: 10000

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,circuitbreakers,retries,caches
  endpoint:
    health:
      show-details: always
    caches:
      enabled: true
  health:
    circuitbreakers:
      enabled: true
    ratelimiters:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html