spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://postgres:5432/ecommerce_db}
    username: ${DATABASE_USERNAME:ecommerce_user}
    password: ${DATABASE_PASSWORD:ecommerce_pass}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5

  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:29092}
    consumer:
      group-id: inventory-service
      properties:
        session.timeout.ms: 30000
        max.poll.records: 10

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

logging:
  level:
    com.ecommerce.inventory: INFO
    org.springframework.kafka: WARN