global:
  environment: prod
  imageTag: latest
  namespace: techbra-ecommerce

# Infrastructure - Configurações otimizadas para produção
postgres:
  enabled: true
  persistence:
    enabled: true
    size: 50Gi
    storageClass: "gp2"
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi

redis:
  enabled: true
  persistence:
    enabled: true
    size: 20Gi
    storageClass: "gp2"
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 512Mi

kafka:
  enabled: true
  zookeeper:
    persistence:
      enabled: true
      size: 20Gi
      storageClass: "gp2"
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 512Mi
  kafka:
    replicaCount: 3
    persistence:
      enabled: true
      size: 100Gi
      storageClass: "gp2"
    resources:
      limits:
        cpu: 2000m
        memory: 4Gi
      requests:
        cpu: 1000m
        memory: 2Gi
  kafkaUi:
    enabled: true

# Microservices - Configurações de produção
microservices:
  orderService:
    enabled: true
    replicaCount: 5
    image:
      tag: latest
      pullPolicy: Always
    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 512Mi
    autoscaling:
      enabled: true
      minReplicas: 5
      maxReplicas: 20
      targetCPUUtilizationPercentage: 60
    podDisruptionBudget:
      enabled: true
      minAvailable: 3
    networkPolicy:
      enabled: true

  billingService:
    enabled: true
    replicaCount: 5
    image:
      tag: latest
      pullPolicy: Always
    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 512Mi
    autoscaling:
      enabled: true
      minReplicas: 5
      maxReplicas: 20
      targetCPUUtilizationPercentage: 60
    podDisruptionBudget:
      enabled: true
      minAvailable: 3
    networkPolicy:
      enabled: true

  inventoryService:
    enabled: true
    replicaCount: 5
    image:
      tag: latest
      pullPolicy: Always
    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 512Mi
    autoscaling:
      enabled: true
      minReplicas: 5
      maxReplicas: 20
      targetCPUUtilizationPercentage: 60
    podDisruptionBudget:
      enabled: true
      minAvailable: 3
    networkPolicy:
      enabled: true

  bff:
    enabled: true
    replicaCount: 8
    image:
      tag: latest
      pullPolicy: Always
    resources:
      limits:
        cpu: 1500m
        memory: 2Gi
      requests:
        cpu: 750m
        memory: 1Gi
    autoscaling:
      enabled: true
      minReplicas: 8
      maxReplicas: 30
      targetCPUUtilizationPercentage: 50
    podDisruptionBudget:
      enabled: true
      minAvailable: 4
    networkPolicy:
      enabled: true

# Monitoring (habilitado em produção)
monitoring:
  prometheus:
    enabled: true
  grafana:
    enabled: true
  jaeger:
    enabled: true